---
language: python
python: "2.7"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r test-requirements.txt

before_script: "flake8 --ignore=E402 --max-line-length=100 --exclude=onetimesecret/py_onetimesecret --show-source --count ."

script: "python setup.py test"
